language: node_js
node_js:
  - 0.10
before_install:
  - npm install phantomjs --save-dev
  - git clone https://github.com/ecomfe/saber-lang.git test/dep/saber-lang/0.4.0
  - git clone https://github.com/ecomfe/saber-uri.git test/dep/saber-uri/0.1.3
install: true
